package com.example.testingautomatico;

/*import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;*/

// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
import org.openqa.selenium.WebElement;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class MusimundoTest {
    
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @BeforeAll
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void musimundoTest() {
    // se abre la URL
    driver.get("https://www.musimundo.com/climatizacion/calefactores/calefactor-sin-salida-orbis-4044go/p/00268035?bdwsearch=true");
    
    // se ajusta el tamaño de la ventana
    driver.manage().window().setSize(new Dimension(1054, 808));
    
    // se agrega el producto al carrito de compras dos veces
    driver.findElement(By.id("addToCartButton")).click();
    driver.findElement(By.id("cboxOverlay")).click();
    driver.findElement(By.id("addToCartButton")).click();
    
    // se abre el carrito de compras
    driver.findElement(By.cssSelector(".miniCart .icons-sprite")).click();
    
    // precio unitario del producto
    WebElement elementoPrecioUnitario = driver.findElement(By.cssSelector(".mus-pro-price-number"));
    
    // subtotal de la compra 
    WebElement elementoSubtotal = driver.findElement(By.cssSelector(".mus-pro-total"));
    
    // visualización de los valores en la consola
    System.out.println("Precio unitario: " + elementoPrecioUnitario.getText());
    System.out.println("Subtotal: " + elementoSubtotal.getText());
  }
  
}
